spring:
  datasource:
    url: jdbc:oracle:thin:@10.11.11.5:1539:cmstest
    username: OPENGATEV2
    password: mxp
    driver-class-name: oracle.jdbc.driver.OracleDriver
keycloak:
  enabled: false
  realm: master
  auth-server-url: http://10.11.11.10:5030
  resource: AWASH_MOB_APP
  ssl-required: external
  bearer-only: true
  use-resource-role-mappings: true
logging:
  file:
    name: /home/opengate/Logs/opengate.log